import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
export default function Home({ data }) {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {data.map((item) => (
            <li key={item.id}>
              <span>{item.title}</span>
              <span>{item.description}</span>
              <span>{item.year}</span>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}

// get movie data with prisma
export async function getServerSideProps() {
  const movies = await prisma.movie.findMany();

  return {
    props: {
      data: movies,
    },
  };
}
